security:
    enable_authenticator_manager: true
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Entity\Utilisateur:
            algorithm: auto

    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\Utilisateur
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            form_login:
                    login_path: login
                    check_path : login
                    default_target_path: /accueil
            logout:
                path: app_logout
                target: /accueil

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#the-firewall

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true
    role_hierarchy:
        ROLE_USER:       [ROLE_PATIENT,ROLE_MEDECIN,ROLE_ASSISTANT]
        ROLE_HOPITAL : [ROLE_MEDECIN,ROLE_ASSISTANT]

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
         - { path: ^/logout, roles: ROLE_USER }
         - { path: ^/patient, roles : ROLE_PATIENT }
         - { path: ^/creerConsultation, roles : ROLE_PATIENT }
         - { path: ^/modifConsultation, roles : ROLE_PATIENT }
         - { path: ^/removeConsultation, roles : ROLE_PATIENT }
         - { path: ^/indisponibilites, roles : ROLE_PATIENT }
         - { path: ^/indisponibilite/(email), roles : ROLE_PATIENT }
         - { path: ^/consultation, roles: ROLE_MEDECIN }
         - { path: ^/consultations/(date), roles: ROLE_MEDECIN } 
         - { path: ^/indisponibilites, roles: ROLE_MEDECIN } 
         - { path: ^/creerIndisponibilite, roles: ROLE_MEDECIN }
         - { path: ^/indisponibilite/(email), roles: ROLE_MEDECIN }  
         - { path: ^/consultation, roles: ROLE_ASSISTANT}
         - { path: ^/validation,  roles: ROLE_HOPITAL}